import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { Providers } from './providers';
import LogoutButton from '@/components/LogoutButton';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const isApplicant = session?.user?.role === 'APPLICANT';
  const isAdmin = session?.user?.role === 'ADMIN';
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-100 p-4 flex gap-4 items-center">
          <Link href="/">Jobfair</Link>
          <Link href="/companies">Perusahaan</Link>
          {!session && <Link href="/register">Register</Link>}
          {!session && <Link href="/login">Login</Link>}
          {isApplicant && <Link href="/dashboard">Dashboard</Link>}
          {isApplicant && <Link href="/profile">Profil</Link>}
          {isAdmin && <span className="text-gray-400">Admin Mode</span>}
          {isAdmin && <Link href="/scan">Scan QR</Link>}
          {session && <LogoutButton />}
        </nav>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
